#!/bin/mksh

[ -n "$DEVNAME" ] || exit 0
[ "$SUBSYSTEM" = "dvb" ] || exit 0

DEVNAME_BASENAME=$(basename ${DEVNAME})
DVBDEVPATH=$(dirname "${DEVNAME}")
DVBPATH=$(dirname "${DVBDEVPATH}")

case "$ACTION" in
	add|"")
		mkdir -p ${DVBDEVPATH}
		mv ${DEVNAME_BASENAME} ${DVBDEVPATH}
		;;
	remove)
		rm -f ${DEVNAME}
		rmdir ${DVBDEVPATH} 2>/dev/null
		rmdir ${DVBPATH} 2>/dev/null
esac

exit 0

